### ISSUE TITLE
MemProcFS

### ISSUE THREAD

**Issue by erdejong** [cristianzsh/forensictools#1]
Can you please add MemProcFS to your list of tools, for me it has been a gamechanger!
https://github.com/ufrisk/MemProcFS

**Comment by cristianzsh** [comment]
Hello, @erdejong. That's a cool tool! I will include it in the 1.1 version. Stay tuned!

Thanks!

**Comment by cristianzsh** [comment]
Closed 51392d0a4a2cd7c01a4e2ec9f8b8db2362e6b83d
