### ISSUE TITLE
Timeline Explorer

### ISSUE THREAD

**Issue by alexzorila** [cristianzsh/forensictools#6]
Could you please add Eric Zimmerman's Timeline Explorer?
https://ericzimmerman.github.io/#!index.md

**Comment by cristianzsh** [comment]
I will include Timeline Explorer in the 1.1 version. Thanks!

**Comment by cristianzsh** [comment]
Closed 51392d0a4a2cd7c01a4e2ec9f8b8db2362e6b83d
