### ISSUE TITLE
The Sleuth Kit

### ISSUE THREAD

**Issue by alexzorila** [cristianzsh/forensictools#7]
Could you please add The Sleuth Kit, or parts of it such as fls, icat, istat?
https://www.sleuthkit.org/sleuthkit/download.php

**Comment by cristianzsh** [comment]
I am currently working on the 1.1 version and The Sleuth Kit is already in. Thank you!

**Comment by cristianzsh** [comment]
Closed 51392d0a4a2cd7c01a4e2ec9f8b8db2362e6b83d
